"""Build data/extraction/Modelfile.fewshot from hard residual examples.

No GPU required: bakes system prompt + few-shot MESSAGE pairs into an Ollama
model derived from a small base (default qwen2.5:0.5b).

Run:
  python -m scripts.build_kharcha_modelfile
  ollama create kharcha-extract -f data/extraction/Modelfile.fewshot
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.extraction import extract_prepass

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "extraction"
TRAIN = DATA / "train.jsonl"
OUT = DATA / "Modelfile.fewshot"

# Prefer tiny specialist base for residual-path latency; override via CLI.
DEFAULT_BASE = "qwen2.5:1.5b"
FEWSHOT_COUNT = 12
FRIENDS = ["Rahul", "Priya"]
CATEGORIES = ["Food", "Transport", "Rent", "Shopping", "Entertainment", "Other"]

SYSTEM = (
    "Extract one expense from a short Hinglish transcript. "
    "Reply with one JSON object only. Keys: amount_rupees, description, "
    "category_name, friend_names, split, spent_on. "
    "spent_on must be YYYY-MM-DD or null. Use only friend names from the Friends list."
)


def load_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _assistant(row: dict) -> str:
    amount_paise = row.get("amount_paise")
    amount_rupees: int | float | None
    if amount_paise is None:
        amount_rupees = None
    else:
        rupees = amount_paise / 100.0
        amount_rupees = int(rupees) if float(rupees).is_integer() else rupees
    payload = {
        "amount_rupees": amount_rupees,
        "description": row["transcript"][:120],
        "category_name": row.get("category_name") or "Other",
        "friend_names": list(row.get("friend_names") or []),
        "split": bool(row.get("wants_split")),
        "spent_on": None,
    }
    return json.dumps(payload, ensure_ascii=False)


def _user(row: dict) -> str:
    pre = extract_prepass(row["transcript"])
    return (
        f"Transcript: {row['transcript']!r}\n"
        f"Hints: amount_paise={pre.amount_paise}, split={pre.wants_split}, "
        f"category={pre.category_name}\n"
        f"Friends: {FRIENDS}\n"
        f"Categories: {CATEGORIES}\n"
        f"JSON keys: amount_rupees, description, category_name, friend_names, split, spent_on"
    )


def pick_fewshot(rows: list[dict], n: int) -> list[dict]:
    """Prefer residual (prepass missed amount) then Other / no_amount / spoken."""
    residual = [
        r for r in rows if extract_prepass(r["transcript"]).amount_paise is None
    ]
    other = [r for r in rows if r.get("category_name") == "Other"]
    spoken = [r for r in rows if "spoken" in (r.get("bucket") or "")]
    picked: list[dict] = []
    seen: set[str] = set()

    def add(pool: list[dict]) -> None:
        for r in pool:
            if len(picked) >= n:
                return
            if r["id"] in seen:
                continue
            seen.add(r["id"])
            picked.append(r)

    add(residual)
    add(other)
    add(spoken)
    add(rows)
    return picked


def _escape_modelfile(text: str) -> str:
    """Ollama MESSAGE bodies: wrap in triple quotes; escape embedded triples."""
    return text.replace('"""', '\\"\\"\\"')


def build_modelfile(base: str, examples: list[dict]) -> str:
    lines = [
        f"# Auto-generated by scripts/build_kharcha_modelfile.py — do not hand-edit.",
        f"# ollama create kharcha-extract -f data/extraction/Modelfile.fewshot",
        f"",
        f"FROM {base}",
        f"",
        f"PARAMETER temperature 0",
        f"PARAMETER num_predict 192",
        f"",
        f'SYSTEM """{_escape_modelfile(SYSTEM)}"""',
        f"",
    ]
    for row in examples:
        user = _escape_modelfile(_user(row))
        assistant = _escape_modelfile(_assistant(row))
        lines.append(f'MESSAGE user """{user}"""')
        lines.append(f'MESSAGE assistant """{assistant}"""')
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    base = DEFAULT_BASE
    if len(sys.argv) > 1:
        base = sys.argv[1]

    if not TRAIN.is_file():
        print(f"Missing {TRAIN}; run: python -m scripts.generate_extraction_corpus")
        sys.exit(1)

    rows = load_jsonl(TRAIN)
    examples = pick_fewshot(rows, FEWSHOT_COUNT)
    text = build_modelfile(base, examples)
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}  (FROM {base}, {len(examples)} few-shot pairs)")
    for ex in examples:
        pre = extract_prepass(ex["transcript"])
        print(f"  - {ex['id']}: amount_hint={pre.amount_paise}  {ex['transcript'][:50]!r}")


if __name__ == "__main__":
    main()
